{
    'name': 'Hospital management',
    'version': '1.0.0',
    'category': 'Extra Tools',
    'summary': 'Module used for management of treating patient',
    'author': 'Odolution',
    'license': 'LGPL-3',
    'sequence': '-100',
    'depends': ["mail",
                "report_xlsx"
                ],
    'demo': [],
    'data': [
        "security/ir.model.access.csv",
        "data/cron.xml",
        "data/data.xml",
        "data/om_hospital.department.csv",
        "wizard/patient_report_view.xml",
        "wizard/appointment_delete_wizard.xml",
        "views/menu.xml",
        "views/pateint_view.xml",
        "views/female_pateint_view.xml",
        "views/appointment_view.xml",
        "views/doctor_view.xml",
        "views/department_view.xml",
        "report/patient_card.xml",
        "report/patient_details_template.xml",
        "report/report.xml"
        ],
    'images': ['images/1.PNG', 'images/2.PNG', 'images/3.PNG','images/4.PNG','static/description/icon.png'],
    'installable': True,
    'application': True,
}
